# Imagen base de Nginx
FROM nginx:alpine

# Copiar archivos de la app al directorio que Nginx sirve por defecto
COPY . /usr/share/nginx/html

# Exponer puerto 80
EXPOSE 80

# Comando por defecto para correr Nginx
CMD ["nginx", "-g", "daemon off;"]