# Imagen base de Nginx
FROM nginx:alpine

# Copiar archivos compilados al contenedor
COPY . /usr/share/nginx/html

# Exponer puerto 80
EXPOSE 80

# Mantener Nginx corriendo
CMD ["nginx", "-g", "daemon off;"]